years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
setting = {
    'region': 'Tropical Asia',
    'good_models':['CABLE-POP','OCN'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    #'REMOTEC':'/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    #'ACOS':'/home/mhuang/data/trendy/v11/acos.nc4',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_1x1.nc',
    'NIRvGPP':'nirv_based_gpp_rf_1x1.nc',
    'AsiaFLux':[[101.2, 21.95], [101.9163, 14.4923], [103.3914, -1.693],[114.03905, 4.201]]
}
Tropical_asia_mainland_setting = {
    'region': 'Tropical Asia mainland',
    'ok_models':['DLEM'], #'CLASSIC','OCN','ORCHIDEE'
    'good_models':['CLASSIC','OCN','ORCHIDEE'],
    # 2014-2015: ['DLEM','CLASSIC','ISBA-CTRIP']
    # 2009-2016: ['DLEM','VISIT-NIES'],['CLASSIC','ISBA-CTRIP','OCN','ORCHIDEE']
    # 2016-2019: ['DLEM'],['CLASSIC','OCN','ORCHIDEE','VISIT-NIES']
    # 2016-2017: ['CABLE-POP','CLASSIC','OCN','ORCHIDEE',]
    # LAI 'CLASSIC', 'ISBA-CTRIP', 'JULES', 'OCN', 'ORCHIDEE'
    # SIF 'CLM5.0','DLEM','LPJ','LPX-Bern','SDGVM','VISIT','YIBs'
    # SIF & GPP 'DLEM'
    # modis land cover 0 SIF: 'CABLE-POP','DLEM','JSBACH','LPX-Bern','SDGVM','VISIT','YIBs'
    # modis land cover 1 SIF: 'LPJ','SDGVM','VISIT','YIBs'                                                              NBP: 'LPJ'
    # modis land cover 3 SIF: 'IBIS','LPJ','LPX-Bern','SDGVM', 'YIBs'                                                   NBP: 'LPJ'
    # modis land cover 4 SIF: 'CABLE-POP','CLM5.0','DLEM','ISAM','JSBACH','LPJ','LPX-Bern','SDGVM','VISIT','YIBs'       NBP: 'DLEM'
    # modis land cover 5 SIF: 'CABLE-POP','CLM5.0','DLEM','ISAM','JSBACH','LPX-Bern','SDGVM','VISIT','YIBs'
    # modis land cover 6 SIF: 'CABLE-POP','CLM5.0','IBIS','ISAM','LPX-Bern','VISIT','VISIT-NIES','YIBs'
    # modis land cover 10SIF: 'CLASSIC','CLM5.0','DLEM', 'ISBA-CTRIP','JULES','JSBACH','LPJ','LPX-Bern','OCN','ORCHIDEE','VISIT','SDGVM'
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
    #'est_GPP':'sif_based_gpp_1x1.nc',
    #'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
    'AsiaFLux':[[101.2, 21.95], [101.9163, 14.4923]]
}
Tropical_asia_islands_setting = {
    'region': 'Tropical Asia islands',
    'good_models':['CLM5.0','DLEM','IBIS'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
aus = {
    'region': 'Australia',
    'good_models':['JSBACH','CLASSIC','LPJ','YIBs','OCN'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_aus.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_aus.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
North_american_temperate = {
    'region': 'North American Temperate',
    'good_models':['IBIS','LPX-Bern','VISIT','SDGVM','ISBA-CTRIP','CLM5.0'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
South_africa = {
    'region': 'Southern Africa',
    'good_models':['CABLE-POP','ORCHIDEE'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v9',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC':'/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS':'/home/mhuang/data/trendy/v11/acos.nc4',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa = {
    'region': 'Northern Africa',
    'good_models':['CABLE-POP','ISAM','ISBA-CTRIP','JULES','JSBACH','LPJ','LPX-Bern','ORCHIDEE','SDGVM'],
    'ok_models':['CLASSIC','DLEM','IBIS','YIBs','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'sif_based_gpp_rf_1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz = {
    'region': 'Northern Africa itcz',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_Mediterranean = {
    'region': 'Northern Africa Mediterranean',
    'good_models':['CABLE-POP','ISAM','ISBA-CTRIP','JULES','JSBACH','LPJ','LPX-Bern','ORCHIDEE','SDGVM'],
    'ok_models':['CLASSIC','DLEM','IBIS','YIBs','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz_south = {
    'region': 'Northern Africa itcz south',
    'good_models':['LPX-Bern'], #'SDGVM','YIBs'  'IBIS'Rh???
    'ok_models':[], #'ISBA-CTRIP','CLASSIC','CABLE-POP'
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz_mid = {
    'region': 'Northern Africa itcz mid',
    'good_models':['LPX-Bern','LPJ'], #'LPJ', 'SDGVM', 'JSBACH',
    'ok_models':['ISAM', 'ISBA-CTRIP'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz_north = {
    'region': 'Northern Africa itcz north',
    'good_models':['CLM5.0'],
    'ok_models':[],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz_east = {
    'region': 'Northern Africa itcz east',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Northern_africa_itcz_west = {
    'region': 'Northern Africa itcz west',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_00S20N_east = {
    'region': 'Africa 00S20N east',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_00S20N_west = {
    'region': 'Africa 00S20N west',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_05S15N_east = {
    'region': 'Africa 05S15N east',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_05S15N_west = {
    'region': 'Africa 05S15N west',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_10S10N_east = {
    'region': 'Africa 10S10N east',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
africa_10S10N_west = {
    'region': 'Africa 10S10N west',
    'good_models':['ISAM','CABLE-POP'],
    'ok_models':['ISBA-CTRIP','CLASSIC','JSBACH'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA5.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa = {
    'region': 'Africa',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Central_Africa = {
    'region': 'Central Africa',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa_05N13N = {
    'region': 'Africa 05N13N',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa_05N15N = {
    'region': 'Africa 05N15N',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa_05N20N = {
    'region': 'Africa 05N20N',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa_05N20N_east = {
    'region': 'Africa 05N20N east',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Africa_05N20N_west = {
    'region': 'Africa 05N20N west',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}
Ethiopia = {
    'region': 'Ethiopia',
    'good_models':['LPJ', 'SDGVM', 'ISBA-CTRIP', 'JSBACH','ISAM','LPX-Bern'], # LPX-Bern?
    'ok_models':[],
    'overes_models':['CABLE-POP','DLEM','IBIS','YIBs','CLASSIC'],
    'shift_models':['JSBACH','OCN'],
    'start_date':'2009-01-01',
    'end_date':'2018-12-31',
    'year':['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019'],
    'path':'/home/mhuang/data/trendy/v11',
    'nbp':'nbp_ensemble.nc',
    'gpp':'gpp_ensemble.nc',
    'ra':'ra_ensemble.nc',
    'rh':'rh_ensemble.nc',
    'fFire':'fFire_ensemble.nc',
    'fLuc':'fLuc_ensemble.nc',
    'lai':'lai_ensemble.nc',
    'TM5GOSAT_fname':'GOSAT_nbp.nc',
    'TM5insitu_fname':'IS_nbp.nc',
    'firedataset_fname':'Global_Fire.nc',
    'SIF_fname':'GOME_sif.nc',
    'FLUXCOM_fname':'FLUXCOM.nc',
    'FLUXCOM_X_fname':'FLUXCOM_X.nc',
    'ERA5_fname':'ERA51x1.nc',
    'OBSPACK':'/mnt/data/users/eschoema/ObsPack_CO2_GLOBALVIEWplusv7.0/obspack_co2_1_GLOBALVIEWplus_v7.0_2021-08-18/data/nc/SationsList.csv',
    'REMOTEC': '/home/mhuang/data/trendy/v11/remotec_NAf.csv',# '/mnt/data/users/eschoema/GOSAT/NetCDF_files_withCH4/fp_short_fil_corr_201202_',
    'ACOS': '/home/mhuang/data/trendy/v11/acos_NAf.csv',#'/home/mhuang/data/trendy/v11/acos.nc4',
    'TM5-4DVAR':'/home/mhuang/data/nontrendy/TM5',
    'CAMS':'/home/mhuang/data/nontrendy/CAMS',
    'CarbonTracker':'/home/mhuang/data/nontrendy/',
    'MODIS_fname':'MODIS_lai.nc',
    'est_GPP':'SIFGPP_ensemble1x1.nc',
    'NIRvGPP': 'nirv_based_gpp_rf_1x1.nc',
}